name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: "./"
        name: Build
        with:
          command: "build"
          arguments: "--path fixture"